###
PUT localhost:8080/offers/configuration/103
Content-Type: application/json

{
  "value": "ARCHIVED"
}





###
POST localhost:8080/offers/configuration
Content-Type: application/json

{
  "offerName": "Отвезу вас на визаран (Черногория)",
  "properties": [
    {
      "name": "Укажи город отправления",
      "type": "STRING",
      "constraint": {
        "type": "SELECTOR_STRING",
        "values": [
          "Бар",
          "Петровац",
          "Будва",
          "Котор",
          "Тиват",
          "Подгорица"
        ]
      }
    },
    {
      "name": "Укажи место остановки",
      "type": "STRING",
      "constraint": {
        "type": "SELECTOR_STRING",
        "values": [
          "До границы с Боснией",
          "Требинье с заездом в молл",
          "Мостар с экскурсией",
          "До границы с Албанией",
          "До границы с Сербией"
        ]
      }
    },
    {
      "name": "Стоимость за пассажира (евро)",
      "type": "INTEGER",
      "constraint": {
        "type": "GREATER_OR_LESS_INTEGER",
        "values": [
          {
            "key": "GREATER_OR_EQUAL",
            "value": 1
          },
          {
            "key": "LESS_OR_EQUAL",
            "value": 200
          }
        ]
      }
    },
    {
      "name": "Какую у тебя машина?",
      "type": "STRING",
      "constraint": {
        "type": "SELECTOR_STRING",
        "values": [
          "Минивен",
          "Легковушка",
          "Внедорожник",
          "Мопед"
        ]
      }
    }
  ]
}